services:
  app:
    build:
      context: .
    image: goupil:latest
    container_name: goupil
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - goupil_postgres
    volumes:
      - ./uploads:/app/uploads

  goupil_postgres:
    image: postgres:18.1@sha256:1090bc3a8ccfb0b55f78a494d76f8d603434f7e4553543d6e807bc7bd6bbd17f
    container_name: goupil_postgres
    restart: unless-stopped
    volumes:
      - ./goupil_db:/var/lib/postgresql
      - ./BDD/database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file: .env

  adminer:
    image: adminer:5.5.0@sha256:494d4a9461105644222c938679fe58d5e3fd13fb228c76a426e81c16d4ffbaef
    container_name: adminer
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - goupil_postgres

  mailhog:
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea # Non mis à jour depuis 6 ans mais fonctionne toujours pour du local
    container_name: mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
